#dein.toml

#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#hook_post_update = '''
#  	if dein#util#_is_windows()
#        let cmd = 'tools\\update-dll-mingw'
#    elseif dein#util#_is_cygwin()
#        let cmd = 'make -f make_cygwin.mak'
#  	elseif executable('gmake')
#        let cmd = 'gmake'
#    else
#        let cmd = 'make'
#    endif
#    let g:dein#plugin.build = cmd
#'''
#
#[[plugins]]
#repo = 'Shougo/vimshell'
#on_source = 'vimproc.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

# unite
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends = ['unite.vim']

# comment
[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-syntastic/syntastic'

# ruby
#[[plugins]]
#repo = 'tpope/vim-rails'
#on_ft = ['ruby', 'rb']
#
#[[plugins]]
#repo = 'vim-ruby/vim-ruby'
#on_ft = ['ruby', 'rb']

# markdown
#[[plugins]]
#repo = 'godlygeek/tabular'
#on_ft = ['markdown', 'md']

# [[plugins]]
# repo = 'previm/previm'
# on_ft = ['markdown', 'md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'md']

# toml
#[[plugins]]
#repo = 'cespare/vim-toml'
#on_ft = 'toml'

# yaml
#[[plugins]]
#repo = 'stephpy/vim-yaml'
#on_ft = ['yaml', 'yml']

# python
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'py'
